/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thi;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class quanLyOto extends javax.swing.JFrame {

    List<oto> list = new ArrayList<>();
    DefaultTableModel defaultTable = new DefaultTableModel();

    /**
     * Creates new form quanLyOto
     */
    public quanLyOto() {
        initComponents();
        //thay doi combobox
        String[] xuatXu = {"MY", "VIETNAM", "TRUNGQUOC", "NHATBAN"};
        cboXuatXu.setModel(new DefaultComboBoxModel(xuatXu));
        // đổ dữ liệu lên bảng
        danhSachMacDinh();
        // tao ket noi dua DefaultTableModel va JTable
        defaultTable = (DefaultTableModel) tblds.getModel();
        // Goi phuong thuc do du lieu
//        doDuLieuLenBang();
    }

    public void danhSachMacDinh() {
        list.add(new oto("honda", 12, "VIETNAM", 1, 2023, true));
        list.add(new oto("honda2", 23, "TRUNGQUOC", 2, 2023, false));
        list.add(new oto("honda3", 44, "NHATBAN", 2, 2023, true));
        list.add(new oto("honda4", 10, "MY", 1, 2023, false));
        list.add(new oto("honda5", 5, "VIETNAM", 1, 2023, true));
    }
    
    public void doDuLieuLenBang() {
        defaultTable.setRowCount(0);
        for(oto item : list) {
            defaultTable.addRow(new Object[] {item.getHang(), item.getTuoi(), item.getXuatXu(),
                item.getKichco() == 1 ? "To" : "Be", item.getNamPH(), item.isTt()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btlKichco = new javax.swing.ButtonGroup();
        btltrangthai = new javax.swing.ButtonGroup();
        lblTieuDe = new javax.swing.JLabel();
        lblHang = new javax.swing.JLabel();
        lbltuoi = new javax.swing.JLabel();
        lblNamph = new javax.swing.JLabel();
        lblXuatxu = new javax.swing.JLabel();
        txtHang = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        txtNamPh = new javax.swing.JTextField();
        cboXuatXu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rdoTo = new javax.swing.JRadioButton();
        rdobe = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        chkMoi = new javax.swing.JCheckBox();
        chkCu = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblds = new javax.swing.JTable();
        btlHienThi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTieuDe.setText("Của hàng ô tô");

        lblHang.setText("Hãng");

        lbltuoi.setText("Tuoi");

        lblNamph.setText("NamPh");

        lblXuatxu.setText("Xuatxu");

        cboXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kich co");

        btlKichco.add(rdoTo);
        rdoTo.setText("To");

        btlKichco.add(rdobe);
        rdobe.setText("Be");

        jLabel1.setText("Trang thai");

        btltrangthai.add(chkMoi);
        chkMoi.setText("moi");

        btltrangthai.add(chkCu);
        chkCu.setText("cu");

        tblds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hang", "Tuoi", "Xuat xua", "Kich thuoc", "Nam phat hanh", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblds);

        btlHienThi.setText("hienThi");
        btlHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlHienThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(lblTieuDe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbltuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNamph)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtNamPh, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoTo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdobe, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblXuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkMoi)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkCu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btlHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHang)
                    .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btlHienThi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbltuoi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamph)
                    .addComponent(txtNamPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblXuatxu)
                    .addComponent(cboXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoTo)
                    .addComponent(rdobe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkMoi)
                    .addComponent(chkCu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlHienThiActionPerformed
        // TODO add your handling code here:
        // Goi phuong thuc do du lieu
        doDuLieuLenBang();
        oto dong2 = list.get(1);
        txtHang.setText(dong2.getHang());
        txtNamPh.setText(dong2.getNamPH()+"");
        txtTuoi.setText(dong2.getTuoi()+"");
        if(dong2.getKichco() == 1) {
            rdoTo.setSelected(true);
        } else {
            rdobe.setSelected(true);
        }
        
        cboXuatXu.setSelectedItem(dong2.getXuatXu());
    }//GEN-LAST:event_btlHienThiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLyOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLyOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLyOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLyOto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLyOto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlHienThi;
    private javax.swing.ButtonGroup btlKichco;
    private javax.swing.ButtonGroup btltrangthai;
    private javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JCheckBox chkCu;
    private javax.swing.JCheckBox chkMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHang;
    private javax.swing.JLabel lblNamph;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXuatxu;
    private javax.swing.JLabel lbltuoi;
    private javax.swing.JRadioButton rdoTo;
    private javax.swing.JRadioButton rdobe;
    private javax.swing.JTable tblds;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtNamPh;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
