/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Day5;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class De4 extends javax.swing.JFrame {

    List<LapTop> dsLapTop = new ArrayList<>();
    DefaultTableModel defaultTable = new DefaultTableModel();
    LapTopService service = new LapTopService();

    /**
     * Creates new form De4
     */
    public De4() {
        initComponents();
        // COMBO BOX : Asus, Dell, Mac, HP, Lenovo
        // HIỂN THỊ DỮ LIỆU 1 SẢN PHẨM LÊN FORM
        LapTop lapTop = new LapTop("Yoga", 21000, "Lenovo", 1, true);
        hienThiLenForm(lapTop);
        // HIỂN THỊ 2 SẢN PHẨM LÊN TABLE
        // tạo liên kết giữa defaultTable và JTable
        defaultTable = (DefaultTableModel) tblDSLapTop.getModel();
        // tạo danh sách mặc định
        dsLapTop.add(new LapTop("M2", 33000, "Mac", 1, false));
        dsLapTop.add(new LapTop("HP V3", 17000, "HP", 2, true));
        hienThiLenBang();
        // Hiển thị đối tượng dòng thứ 2 lên form
        // index = 2 -1 = 1
        hienThiLenForm(dsLapTop.get(1));
    }

    // hiển thị lên form
    public void hienThiLenForm(LapTop lt) {
        txtTen.setText(lt.getTen());
        txtGia.setText(lt.getGia() + "");
        cboHang.setSelectedItem(lt.getHang());
        if (lt.getoCung() == 1) {
            rdoSSD.setSelected(true);
        } else {
            rdoHDD.setSelected(true);
        }
        chkTrangThai.setSelected(lt.isTrangThai());
    }

    // hiển thị ds lên bảng
    public void hienThiLenBang() {
        if (dsLapTop.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống!!!");
        } else {
            // reset bảng về dòng đầu tiên
            defaultTable.setRowCount(0);
            for (LapTop it : dsLapTop) {
                defaultTable.addRow(new Object[]{it.getTen(), it.getGia(), it.getHang(),
                    it.getoCung() == 1 ? "SSD" : "HDD", it.isTrangThai()
                });
            }
        }
    }
    // hiển thị ds lên bảng

    public void hienThiLenBang(List<LapTop> list) {
        if (dsLapTop.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách trống!!!");
        } else {
            // reset bảng về dòng đầu tiên
            defaultTable.setRowCount(0);
            for (LapTop it : list) {
                defaultTable.addRow(new Object[]{it.getTen(), it.getGia(), it.getHang(),
                    it.getoCung() == 1 ? "SSD" : "HDD", it.isTrangThai()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboHang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rdoSSD = new javax.swing.JRadioButton();
        rdoHDD = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        chkTrangThai = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLapTop = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý LAPTOP");

        jLabel2.setText("Tên");

        jLabel3.setText("Giá");

        jLabel4.setText("Hãng");

        cboHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asus", "Dell", "Mac", "HP", "Lenovo" }));

        jLabel5.setText("Ổ cứng");

        buttonGroup1.add(rdoSSD);
        rdoSSD.setText("SSD");

        buttonGroup1.add(rdoHDD);
        rdoHDD.setText("HDD");

        jLabel6.setText("Trạng Thái");

        chkTrangThai.setText("Mới");

        tblDSLapTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "Giá", "Hãng", "Ổ cứng", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDSLapTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSLapTopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSLapTop);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkTrangThai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdoSSD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rdoHDD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cboHang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSapXep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdoSSD)
                            .addComponent(rdoHDD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chkTrangThai)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSapXep)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtTen.setText("");
        txtGia.setText("");
        cboHang.setSelectedIndex(0);
        buttonGroup1.clearSelection();// Xóa giá trị các nút trong group
        chkTrangThai.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblDSLapTopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSLapTopMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblDSLapTop.getSelectedRow();
        if (rowIndex >= 0) {
            // Hiển thị thông tin dòng được chọn lên form
            hienThiLenForm(dsLapTop.get(rowIndex));
        }
    }//GEN-LAST:event_tblDSLapTopMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String ten = txtTen.getText();
        String gia = txtGia.getText();
        if (ten.isEmpty() || gia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên và giá không được để trống");
        } else if (service.isChuoi(ten) == false) {
            JOptionPane.showMessageDialog(this, "Tên không đúng định dạng");
        } else if (!new LapTopService().isSoThuc(gia)) {
            JOptionPane.showMessageDialog(this, "Giá không đúng định dạng");
        } else {
            LapTop lapTop = layDuLieuTuForm();
            // thêm đối tượng vào danh sách
            dsLapTop.add(lapTop);
            // đổ lại danh sách mới lên table
            hienThiLenBang();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int rowIndex = tblDSLapTop.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Phải chọn dòng cần sửa");
        } else {
            String ten = txtTen.getText();
            String gia = txtGia.getText();
            if (ten.isEmpty() || gia.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên và giá không được để trống");
            } else if (service.isChuoi(ten) == false) {
                JOptionPane.showMessageDialog(this, "Tên không đúng định dạng");
            } else if (!new LapTopService().isSoThuc(gia)) {
                JOptionPane.showMessageDialog(this, "Giá không đúng định dạng");
            } else {
                LapTop lapTop = layDuLieuTuForm();
                // sửa đối tượng vào danh sách với vị trí đã chọn
                dsLapTop.set(rowIndex, lapTop);
                // đổ lại danh sách mới lên table
                hienThiLenBang();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int rowIndex = tblDSLapTop.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Phải chọn dòng cần xóa");
        } else {
            // xóa đối tượng trong danh sách bằng index
            dsLapTop.remove(rowIndex);
            // đổ lại dữ liệu lên ds
            hienThiLenBang();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if (txtTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập tên cần tìm");
        } else {
            List<LapTop> dsTim = service.timBangTen(dsLapTop, txtTen.getText());
            // C1:
//            dsLapTop = dsTim;
//            hienThiLenBang();
            // C2 viết lại hàm đổ dữ liệu lên form
            if (dsLapTop.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Danh sách trống!!!");
            } else {
                // reset bảng về dòng đầu tiên
                defaultTable.setRowCount(0);
                for (LapTop it : dsTim) {
                    defaultTable.addRow(new Object[]{it.getTen(), it.getGia(), it.getHang(),
                        it.getoCung() == 1 ? "SSD" : "HDD", it.isTrangThai()
                    });
                }
            }
            // C3: viết lại hàm hổ dữ liệu có truyền tham số
            hienThiLenBang(dsTim);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        service.sapXep(dsLapTop);
        hienThiLenBang();
    }//GEN-LAST:event_btnSapXepActionPerformed

    // Lấy dữ liệu từ form
    public LapTop layDuLieuTuForm() {
        return new LapTop(txtTen.getText(), Double.parseDouble(txtGia.getText()),
                cboHang.getSelectedItem().toString(),
                rdoSSD.isSelected() ? 1 : 2, chkTrangThai.isSelected());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(De4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(De4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(De4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(De4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new De4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboHang;
    private javax.swing.JCheckBox chkTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoHDD;
    private javax.swing.JRadioButton rdoSSD;
    private javax.swing.JTable tblDSLapTop;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
